---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1674399/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp license.txt $DEPLOYPATH
    - /bin/cp readme.rst $DEPLOYPATH
    - /bin/cp contributing.md $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R tests $DEPLOYPATH
    - /bin/cp -R user_guide $DEPLOYPATH
